version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - jinktic-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jinktic-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  producto-app:
    build:
      context: ./producto
      dockerfile: Dockerfile
    container_name: producto-app
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DOCKER_COMPOSE_ENABLED: false
    networks:
      - jinktic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 120s

  inventario-service:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    container_name: inventario-service
    ports:
      - '8000:8000'
    volumes:
      - ./inventario-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mongo:
        condition: service_healthy
      producto-app:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/inventario_db
      PRODUCTOS_SERVICE_URL: http://producto-app:8080
      INVENTARIO_SERVICE_URL: http://inventario-service:8000
      API_KEY: XYZ123
      PYTHONUNBUFFERED: 1
    networks:
      - jinktic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:
  postgres_data:

networks:
  jinktic-network:
    driver: bridge
